FROM 192.168.100.81:8083/php:7.1.8-apache

RUN pecl install redis && docker-php-ext-enable redis

WORKDIR /root/test/

ADD src /root/test/

RUN ls /root/test/

RUN rm -rf /var/www/html/*

RUN ls /var/www/html/

VOLUME /var/www/html

ADD start.sh /root/

RUN chmod 777 /root/start.sh





